### ISSUE TITLE
Subtype Card - Do we need the Subtype description in the header and display?

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-data-dictionary-viewer#13]

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/67976711-de6f0600-fbd3-11e9-9a87-55de62c94fdf.png)

@MikeMillerGIS Are you talking about overall description vs the asset type descriptions?

**Comment by MikeMillerGIS** [comment]
no idea, logged this 8 months ago
