### ISSUE TITLE
Missing underbar in the box around Domains

### ISSUE THREAD

**Issue by ElenaFernandes** [Esri/solutions-data-dictionary-viewer#21]
When you first open the data dictionary, it appears that there is a line missing below the Domains section.
![image](https://user-images.githubusercontent.com/28354690/56510646-40410b80-64df-11e9-9def-9f526cde313d.png)

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/68885281-b1d5e680-06c9-11ea-9514-a1b0f8f7c14f.png)

Updated in latest build, closing.
