### ISSUE TITLE
Asset Type cards - also to include domain information.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#25]
Include domains information in “Fields” for each one of the fields. Ideally, full domain values are also provided here rather than the user having to find the domain in the separate Domain section. It appears that this has been added for some fields, but I notice that it is missing for assettypes.
![image](https://user-images.githubusercontent.com/50338557/57640851-5125ef80-7568-11e9-943d-43f9c65b9a95.png)

Setup could be similar to this:
![image](https://user-images.githubusercontent.com/50338557/57640870-5daa4800-7568-11e9-89e4-931ff49ca8d2.png)

**Comment by gslyer** [comment]
@avezina Looks like this has been handled. 

![image](https://user-images.githubusercontent.com/28928994/67977094-9d2b2600-fbd4-11e9-9583-e0de1d6d148e.png)

@previnWong this has no domain values? Why?
