### ISSUE TITLE
Display issue - allow for text wrapping.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#26]
For example, asset types under domains are hidden in the pane.
![image](https://user-images.githubusercontent.com/50338557/57641022-c85b8380-7568-11e9-91b0-219cf22251ce.png)

**Comment by gslyer** [comment]
We need to find a better way to handle long element names

**Comment by gslyer** [comment]
@previnWong Let's do a **...** on the names after 30 characters with no breaks if we don't plan on expanding the side panel and 50 if we do plan on expanding the side panel. 

Additionally, the long domain names cause an issue when using the split workspace option it cuts off the heart and X. 
![image](https://user-images.githubusercontent.com/28928994/69441760-216a5800-0d00-11ea-88a6-51841b7597ee.png)


Let's strip out the properties icon and the statistics icon for this release and remove the favorite option. 
![image](https://user-images.githubusercontent.com/28928994/69442228-0c41f900-0d01-11ea-9c41-f86f80deda52.png)

**Comment by previnWong** [comment]
Forced the long names to wrap and also added tooltip to see the name on 1 line.

![image](https://user-images.githubusercontent.com/11183838/72847880-47f13480-3c58-11ea-884a-04b056cd1877.png)

**Comment by gelisajoseph** [comment]
This looks a lot better!

**Comment by gelisajoseph** [comment]
Verified Closing
