### ISSUE TITLE
Issue when switching from 2 to 1 pane.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#27]
When dividing the main stage into 2 panes and adding cards on both sides, all cards included in the right-hand side disappear when switching back to single pane instead of stacking into the single pane.
![image](https://user-images.githubusercontent.com/50338557/57641103-ff319980-7568-11e9-9e6f-2b172e4a3f75.png)
![image](https://user-images.githubusercontent.com/50338557/57641106-0193f380-7569-11e9-9aec-472512a2c2e8.png)

**Comment by gelisajoseph** [comment]
Verified. Closing!
