### ISSUE TITLE
Increase size of + and – symbols or replace with drop down arrow as in other ArcGIS UIs.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#31]
Increase the size of + and – symbols or replace with a drop-down arrow as in other ArcGIS UIs. ( > )
For example: 

![image](https://user-images.githubusercontent.com/50338557/57641409-ce9e2f80-7569-11e9-83d8-919c2df7bcb8.png)

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/67977772-f21b6c00-fbd5-11e9-9592-61d473f56cbe.png)

@avezina Do the arrows in the image above resolve your issue?

**Comment by avezina** [comment]
Looks good!
