### ISSUE TITLE
Add hover text that explains what each button is for on the left-hand side. Also increase size of button by 25%.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#32]
Add hover text that explains what each button is for on the left-hand side. Also increase size of button by 25%.
![image](https://user-images.githubusercontent.com/50338557/57641485-f7bec000-7569-11e9-8996-f9788aaaf36a.png)

**Comment by previnWong** [comment]
tooltips

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73563565-7b7b4e00-4412-11ea-8c5c-3c4dffb2efe1.png)

Added tool tips. Not changing button size. handled by react internally.

**Comment by avezina** [comment]
Nice tooltips. It's a bummer we can't increase button size..

**Comment by previnWong** [comment]
closing
