### ISSUE TITLE
Change "Search Your Service" for "Add Filters

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#33]
![image](https://user-images.githubusercontent.com/50338557/57641525-145af800-756a-11e9-923a-e709c8ebd5b9.png)

**Comment by gslyer** [comment]
@avezina An enhanced filter is being added and should resolve this issue. I will add a screenshot when I get the lastest build.

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/68885607-53f5ce80-06ca-11ea-9556-882000af2456.png)

@avezina Filter added test and provide feedback.

**Comment by avezina** [comment]
A few things that I can see, but no show stopper.

1. Can we align the style to match? I'd remove Time New Roman and use Calibri or something similar.
![image](https://user-images.githubusercontent.com/50338557/68890388-97a10600-06d3-11ea-9fbc-39599dafeebf.png)

2. The behavior of turning filters on/off should be in line with other ArcGIS products. See examples below:
![DataDict-2019-11-14_12-34-21](https://user-images.githubusercontent.com/50338557/68894407-1c901d80-06dc-11ea-9d9c-a24ceb5523f6.gif)
Same is observed in ArcGIS Pro.

3. "Select the elements to include in the search results."
![image](https://user-images.githubusercontent.com/50338557/68894572-64af4000-06dc-11ea-8589-b431c72bd4e5.png)

3. Move the dropdown arrow to the left to allow for a space on the right.
![image](https://user-images.githubusercontent.com/50338557/68894603-78f33d00-06dc-11ea-9da7-34adb250ac18.png)

4. Could we just make it “Search”? It’s implied we’re searching the service.
![image](https://user-images.githubusercontent.com/50338557/68895077-7a713500-06dd-11ea-8142-be9173c3cd59.png)

5. Depending on if we decide this should be a search "settings/options" button or an actual filter, we could use a related icon such as:
![image](https://user-images.githubusercontent.com/50338557/68895267-cd4aec80-06dd-11ea-8129-5e8aa344c354.png) or 
![image](https://user-images.githubusercontent.com/50338557/68895339-e94e8e00-06dd-11ea-8d53-8ab5327621ae.png)

**Comment by gslyer** [comment]
@previnWong Let's do number 1, 3, 4, 5, 6. I can also do this since it's mostly strings.

**Comment by previnWong** [comment]
will do 3, 4,5, and 6

**Comment by previnWong** [comment]
@avezina for number 2, map services don't behave like what I am trying to accomplish.  The header checkbox in the search filter toggles all sub checkboxes on/off.

The map service header groups don't turn sublayers on/off, it's still manual.
https://arcgissolutions.maps.arcgis.com/home/webmap/viewer.html?webmap=0113bc7406224eef91c00640ac28d33b

I agree there's a third state that needs to be shown (some, but not all of the subs are checked). WIll work on that.

**Comment by previnWong** [comment]
Fixed the checkbox toggles. This is the behavior you are expecting.

![checkbox](https://user-images.githubusercontent.com/11183838/73778919-cb268600-4740-11ea-8fde-e57919d88147.gif)

so did 2,3,4,5,6.    Can't do 1, I am not setting font family in the code. that is all React and Jimu core.

**Comment by avezina** [comment]
Nice!!
