### ISSUE TITLE
Add instructional text to main view.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#34]
Add instructional text in the empty view pane (or Main Stage / Main View? - how should we name this/ ). 
Use example from Operations Dashboard:
![image](https://user-images.githubusercontent.com/50338557/57641632-597f2a00-756a-11e9-93ec-e0b31e30a6a0.png)

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73560124-40295100-440b-11ea-9230-aebb957b441d.png)

**Comment by previnWong** [comment]
added. closing
