### ISSUE TITLE
Increase spacing between header and “Subtype Properties” text.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#35]
![image](https://user-images.githubusercontent.com/50338557/57641672-71ef4480-756a-11e9-8f1b-8ee942062617.png)

**Comment by previnWong** [comment]
old
![image](https://user-images.githubusercontent.com/11183838/73484736-b455ed00-4356-11ea-8338-b2f3b6190c30.png)

new
![image](https://user-images.githubusercontent.com/11183838/73484780-c5066300-4356-11ea-9b4b-c21d5fccf884.png)

good or more?

**Comment by avezina** [comment]
I feel so much better now

**Comment by previnWong** [comment]
closing
