### ISSUE TITLE
Change icon for opening a card from within a card.

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#39]
Change how these open. Also, most users recognize this symbol 
![image](https://user-images.githubusercontent.com/50338557/57641838-dc07e980-756a-11e9-8f2b-2f94c6d1cfd3.png)
  as meaning “copy”.

![image](https://user-images.githubusercontent.com/50338557/57641859-e6c27e80-756a-11e9-9199-c13a3c996c56.png)

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/74576662-abf9d680-4f40-11ea-99a3-dc02e0c7bee9.png)
