### ISSUE TITLE
Connectivity rules

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#41]
Add connectivity rules to the Asset Type cards

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/72573866-e7d74880-387b-11ea-8014-13dfac7ba9e9.png)

**Comment by gelisajoseph** [comment]
Verified Closing.

Formating issues are logged here https://github.com/Esri/solutions-data-dictionary-viewer/issues/47
