### ISSUE TITLE
Subtype Properties Card Fields

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#42]
In the fields table, of the subtype properties, we should split out the field name and the alias.
![image](https://user-images.githubusercontent.com/28928994/68415762-eedd2e80-0147-11ea-8b4e-8fff34485040.png)

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/68891101-134f8280-06d5-11ea-930f-54c9690e926a.png)

The AT table has no links to the specific AT

**Comment by previnWong** [comment]
Added link icon to asset types section.  Broke out  FIeld name and ALias in Fields section
![image](https://user-images.githubusercontent.com/11183838/73034633-52e3ca80-3dfa-11ea-8595-796f7c3162d8.png)
