### ISSUE TITLE
Relationship Card update

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#43]
Change from the below card 
![image](https://user-images.githubusercontent.com/28928994/68418448-17b3f280-014d-11ea-803a-b36edddfe9f1.png)

To something like
![image](https://user-images.githubusercontent.com/28928994/68418492-2f8b7680-014d-11ea-9d55-84cb6c7b84e8.png)

**Comment by marshj9** [comment]
I suggest to place the Origin Name and its Primary Key in the same column on the left and the Destination and Origin Foreign Key in the same column on the right.

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/68433307-0d085600-016b-11ea-8743-61eaae5af948.png)

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/72464866-f72a9900-378a-11ea-9abd-8d005d734c60.png)

**Comment by gelisajoseph** [comment]
I'm getting the popup shown in the image when clicking electrical device unit
![image](https://user-images.githubusercontent.com/28928994/72942845-59eed800-3d29-11ea-82e4-cdc73f806c63.png)


Additionally, the rows should not be highlighted all the ways across. 
They should look more like the below image
![image](https://user-images.githubusercontent.com/28928994/72942991-c36ee680-3d29-11ea-8417-9f2bb18a3015.png)

**Comment by gelisajoseph** [comment]
@previnWong This is my bad but can we update **Destination** to **Destination Name**

**Comment by previnWong** [comment]
Sure

**Comment by previnWong** [comment]
Removed highlighting altogether since it's not really a table listing.
![image](https://user-images.githubusercontent.com/11183838/73771841-f656a880-4733-11ea-9ca0-3755d3d1041a.png)
