### ISSUE TITLE
Water Utility Network layer not clickable

### ISSUE THREAD

**Issue by gslyer** [Esri/solutions-data-dictionary-viewer#45]
![image](https://user-images.githubusercontent.com/28928994/68716952-4de0e000-055a-11ea-8675-14a8a4c15d6d.png)

This element is not clickable but the controller dataset element is clickable (same level)

**Comment by previnWong** [comment]
yes.  issue I noted down. question, do we want it listed under layers as well?

**Comment by gslyer** [comment]
resolved closing
