### ISSUE TITLE
Update the Rules table format

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#47]
![image](https://user-images.githubusercontent.com/28928994/68718809-348e6280-055f-11ea-8b1a-51a4ffcaadc0.png)

Change the header to be non-hoverable and make it look like the other table headers. Split out Rules From and Rules to header text to be outside of the tables.

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/72573843-d42be200-387b-11ea-9b98-54bb37b1f511.png)

**Comment by gelisajoseph** [comment]
Something looks a bit odd with the box empty like this
![image](https://user-images.githubusercontent.com/28928994/72825808-912b8f00-3c2c-11ea-9b23-6f04369dddda.png)

- Additionally, if there are no rules should we even show the option to for the rules dropdown option?

Could we do the + symbol in a box for these that changes to a - symbol when clicked similar to the below?
![image](https://user-images.githubusercontent.com/28928994/72825903-bae4b600-3c2c-11ea-86a1-7878b57d0ae0.png)

**Comment by previnWong** [comment]
add message when there is no rules

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73563749-f5abd280-4412-11ea-9363-009b1b3cd478.png)
