### ISSUE TITLE
Add Asset type card

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#48]
![image](https://user-images.githubusercontent.com/28928994/68719438-e11d1400-0560-11ea-88bb-f3650389a323.png)

Currently, there is no Asset Type card and this does not fit the current hierarchy we have set for everything else in the TOC.

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73029595-ae0ec080-3dec-11ea-806c-07ab28ee8ee4.png)

**Comment by previnWong** [comment]
do lookup of asset types for asset type under TABLE nodes

**Comment by previnWong** [comment]
Asset types now listed under TABLE node
![image](https://user-images.githubusercontent.com/11183838/73767869-e9828680-472c-11ea-83c2-ccb17b46a7b4.png)
