### ISSUE TITLE
Network Attribute cards linking for field opens inncorrect card

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#49]
![image](https://user-images.githubusercontent.com/28928994/68719827-0b230600-0562-11ea-91b2-86d1f1bb6fda.png)

![image](https://user-images.githubusercontent.com/28928994/68719912-65bc6200-0562-11ea-97c6-8aeadf855075.png)

**Comment by previnWong** [comment]
implemented in current code in exb_version branch.

**Comment by gelisajoseph** [comment]
Verified closing
