### ISSUE TITLE
Layer cards should have descriptions

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#50]
![image](https://user-images.githubusercontent.com/28928994/69732226-1b012500-10e0-11ea-8c2a-3df4d4c9326f.png)

**Comment by gelisajoseph** [comment]
@previnWong We need to grab the metadata for this card and add it to this card. We need to get this done for the March 24th Release.

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/72829727-2da55f80-3c34-11ea-8947-0049ac05f648.png)

**Comment by gelisajoseph** [comment]
Looks good closing!
