### ISSUE TITLE
Categories Card UI 

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#51]
![image](https://user-images.githubusercontent.com/28928994/72853736-264b7980-3c67-11ea-8607-6b9598122627.png)

The Category cards have a random line above it and the icon to open the card link icon is a bit close to the text.

![image](https://user-images.githubusercontent.com/28928994/72853881-84785c80-3c67-11ea-9464-cdb371c51528.png)
We should update the text when there are no categories.
@avezina What do you think the text should say when there are no categories?

**Comment by avezina** [comment]
Looks great just add a sad face 😞 
No really, maybe just "No categories available" - what's a category supposed to be? asset group? asset type?

**Comment by gelisajoseph** [comment]
@avezina https://pro.arcgis.com/en/pro-app/help/data/utility-network/about-network-categories.htm

**Comment by avezina** [comment]
Then the message should be:
“No network categories available.”

Alix
________________________________

**Comment by gelisajoseph** [comment]
Eh is it not available or are they just not configured for that subtype. We will just leave the wording for now.

**Comment by previnWong** [comment]
Add header to Asset type card  for categories table

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73475183-b2832e00-4344-11ea-8913-c57265231938.png)

**Comment by gelisajoseph** [comment]
Verified closing.
