### ISSUE TITLE
All TOC elements get highlight at same level

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#52]
![image](https://user-images.githubusercontent.com/28928994/73105018-b3334480-3eac-11ea-91f1-29fd783b695f.png)

If you select the Attribute Rules in the TOC for Crossarm it highlights all Attribute Rules elements in the TOC. 

Expected Behavior:
Only the card that has been opened should be highlighted in the TOC.

**Comment by previnWong** [comment]
yep, noticed this. will look into it

**Comment by previnWong** [comment]
![image](https://user-images.githubusercontent.com/11183838/73190711-418d0d80-40db-11ea-9007-8500c0496897.png)

![image](https://user-images.githubusercontent.com/11183838/73190721-45209480-40db-11ea-9bfe-81cb40ead85e.png)

**Comment by gelisajoseph** [comment]
Verified Closing.
