### ISSUE TITLE
Subtype Card - Show layer name on the card so you know which layer it belongs too

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-data-dictionary-viewer#7]

**Comment by gslyer** [comment]
![image](https://user-images.githubusercontent.com/28928994/69442962-52e42300-0d02-11ea-8038-cf154622ac41.png)

A breadcrumb has been added to each card to help you understand what the card is related to.

**Comment by gelisajoseph** [comment]
This has been completed.
