### ISSUE TITLE
Comm version is missing details on the tiers

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-data-dictionary-viewer#70]
https://solutions.arcgis.com/utilities/data-dictionary/index.html?cacheId=6600fb028af84d8b868490adcd53568b

I do not see any of the info for the tiers
![image](https://user-images.githubusercontent.com/2707285/113687800-b4f2bd80-9696-11eb-8300-c69fab085c8d.png)

**Comment by MikeMillerGIS** [comment]
@previnWong

**Comment by MikeMillerGIS** [comment]
verified

**Comment by gelisajoseph** [comment]
@MikeMillerGIS 
![image](https://user-images.githubusercontent.com/28928994/116922729-00a37300-ac13-11eb-88f5-9417cf17d5aa.png)

Do we care that this says pro 2.8 beta 2?

**Comment by MikeMillerGIS** [comment]
we probably should scrub from the cache, that is easy enough to do
