### ISSUE TITLE
Category to Layer link broken

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#73]
1. Open the [DD ](https://solutions.arcgis.com/utilities/data-dictionary/index.html?cacheId=414bf3bd3353474897ef5aab70e153b6) app for Communications 
2. Search "connection" 
3. Open the C:Strand Connection under Categories
4. Click the open card button next to "Communications Junction Object"

Result: Sorry, no card found. This card can be opened from the TOC just not from this specific card.
![image](https://user-images.githubusercontent.com/28928994/116114208-62de0000-a676-11eb-9e4b-c7603ed58d86.png)

Additionally I'm in incognito mode in a new browser.

**Comment by MikeMillerGIS** [comment]
verified
