### ISSUE TITLE
cleanAlais.alias is undefined bug

### ISSUE THREAD

**Issue by gelisajoseph** [Esri/solutions-data-dictionary-viewer#74]
1. Open the [DD ](https://solutions.arcgis.com/utilities/data-dictionary/index.html?cacheId=414bf3bd3353474897ef5aab70e153b6) app for Communications 
2. Search connection point and open the card
3. Click the link next to AssetID

Result: cleanAlais.alias is undefined

**Comment by MikeMillerGIS** [comment]
Cant repo in updated version
