### ISSUE TITLE
Look at a search or filter on the main card page

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-data-dictionary-viewer#8]
this would let me show only Subtype Cards or cards with a key value of X

**Comment by gslyer** [comment]
Searching enhancements will include: 
- [ ] Breadcrumb on each card
- [ ] A filter on all element types 
- [ ] The table of contents hierarchy should be maintained when searching

**Comment by gslyer** [comment]
@previnWong Let's update the search functionality to search the TOC on the click of a search icon and not be dynamic to make the user experience smoother.
![image](https://user-images.githubusercontent.com/28928994/68812734-a41c5480-0628-11ea-86cb-635ef4b91916.png)
.

**Comment by gelisajoseph** [comment]
This has been completed.
