### ISSUE TITLE
Asset Type card is missing descriptions

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-data-dictionary-viewer#83]
They are under the subtype/asset type drop down though

![image](https://github.com/Esri/solutions-data-dictionary-viewer/assets/2707285/ca50d32e-130d-4bdc-9da3-b98c8fec1dfb)

**Comment by MikeMillerGIS** [comment]
Also affects subtypes
https://community.esri.com/t5/arcgis-utility-network-questions/descriptions-in-utility-network-data-dictionary/m-p/1310516#M2616

**Comment by MikeMillerGIS** [comment]
@previnWong we keep hearing this, could we get this updated soon?

**Comment by avezina** [comment]
Fixed 
![image](https://github.com/Esri/solutions-data-dictionary-viewer/assets/50338557/7ae0a6b3-0f26-402c-a6db-bb91b6e69a0b)
